### ISSUE TITLE
你好 demo跑起来了 集成到项目里有问题

### ISSUE THREAD

**Issue by CUIYONGCHUANG** [yale8848/EasyIncrementalUpdate#10]
- Mobile:
- Android OS:
- Lib version:

---

**Comment by yale8848** [comment]
what problem？

**Comment by CUIYONGCHUANG** [comment]
我自己项目里也有ndk配置，把demo里的加进去就有问题，方便加个微信吗13155557305

**Comment by yale8848** [comment]
先把你项目报的相关错误都都贴出来吧，咱看看能解决不？

**Comment by CUIYONGCHUANG** [comment]
![1541127741 1](https://user-images.githubusercontent.com/41567293/47891586-ce242e00-de8e-11e8-874f-d74ae608a85a.jpg)

**Comment by CUIYONGCHUANG** [comment]
您好 我安卓端调用了您的接口传了三个参数进去分别是新包的路径,旧包的路径，补丁包的路径(我的补丁包是同事在服务器上自己打给我的,之前测过能用,安卓端我没用它的,改成了您的,现在log输出这个是什莫意思)

**Comment by yale8848** [comment]
服务端是用我readme里的工具生成的补丁包吗？不是的话，让他用我提供工具生成补丁，windows工具也有，你可以试试生成补丁包，然后再测试；工具不一样，生成的补丁包是不一样的；
