### ISSUE TITLE
你好，使用过程中出了点问题

### ISSUE THREAD

**Issue by LBruse** [yale8848/EasyIncrementalUpdate#11]
在华为Mate10，android 8.0环境上测试,EasyIncrementalUpdate.patch(context,"new apk path","patch file")这个方法返回true,但是在安装new apk的时候,提示解析包错误,这个要怎么解决呢？

**Comment by yale8848** [comment]
你再看看logcat中有没有什么异常信息？

**Comment by LBruse** [comment]
Logcat中没有异常信息。在电脑上对OldAPK和NewApk用bsdiff.exe生成.patch文件,然后用bspatch.exe合并生成新的APK,把这个新的APK放到手机上可以安装,不会提示解析包错误。但是在手机上调用EasyIncrementalUpdate.patch()方法虽然返回true,但是生成的APK无法进行安装,就提示解析包错误。

**Comment by yale8848** [comment]
你看看 ‘new apk path‘ 正常生成apk文件了吗？ 是不是安装权限的问题,7.0 以上有权限问题

**Comment by LBruse** [comment]
不是安装权限的问题。也在android5.1上测试过,能生成newAPK文件,但是APK一样是无法安装，解析包错误。

**Comment by LBruse** [comment]
合成的APK已经损坏了,是这个库的bug吗？

**Comment by yale8848** [comment]
目前的情况看，就是我这个库的bug，我再debug一下...

**Comment by yale8848** [comment]
我这里测试都没有问题，请你再确认一下流程：
1.release打包v1.apk,然后打包v2.apk；
2.bsdiff.exe v1.apk v2.apk patch
3.安装v1.apk,v1加载patch文件合并安装；
注意第三步必须要安装v1.apk测试；

**Comment by LBruse** [comment]
我发现了问题所在，我之前是在android studio运行debug app进行测试的，通过这样的方式生成的APK是有问题的，但是像你说的第3步那样的话，生成出来的APK就没问题。这是为什么呢？debug签名和release签名是一致的。

**Comment by yale8848** [comment]
debug和release生成的apk二进制文件是不一样的，即使用同一个签名，debug时apk里会保留很多debug信息的；两个apk哪怕有一个字节不一样，最后就有可能合并失败；

**Comment by LBruse** [comment]
原来如此,，没想到自己给自己挖坑了...囧
