### ISSUE TITLE
jcenter() 上最新的是1.0.5可能需要更新下

### ISSUE THREAD

**Issue by alexhuahua** [yale8848/EasyIncrementalUpdate#4]
- Mobile:
- Android OS:
- Lib version:

---

**Comment by yale8848** [comment]
抱歉，jcenter上最新的是1.0.5
改过一次lib名字1.1.1没有提交到jcenter，1.0.5的code也新的，可以放心用，等jcenter审核过了，我再更新一下readme，谢谢了

**Comment by yale8848** [comment]
jcenter 更新至1.1.2，你再试试
