### ISSUE TITLE
bsdiff windows下载后无法安装

### ISSUE THREAD

**Issue by liuhedev** [yale8848/EasyIncrementalUpdate#7]
widonws环境下，bsdiff 下载后，点击一闪而过，无法安装。

**Comment by yale8848** [comment]
不需要安装，是命令行程序：

差分命令如下：
bsdiff.exe old.apk new.apk patch

合并命令(可以用来测试)
bspatch.exe old.apk new.apk patch

你是这么测试的吗？

**Comment by liuhedev** [comment]
windows 太难搞了，放弃了，直接linux编译过了。
