### ISSUE TITLE
Failed to resolve: ren.yale.android:intremetalupdate:1.1.2

### ISSUE THREAD

**Issue by lifeidroid** [yale8848/EasyIncrementalUpdate#8]
- Mobile:
- Android OS:
- Lib version:
Failed to resolve: ren.yale.android:intremetalupdate:1.1.2 更新不下来啊
---

**Comment by yale8848** [comment]
```
    repositories {
        jcenter()
    }
```
jcenter 上的，我这测试都ok，是不是网络问题？多试试几次

**Comment by yale8848** [comment]
不好意思，是我拼错了,下面是正确的：
`ren.yale.android:incremetalupdate:1.1.2`
